#!/bin/sh
set -e

case "${1}" in
	purge|remove)
            update-alternatives \
            --remove default.plymouth /lib/plymouth/themes/minos-screwdriver/minos-screwdriver.plymouth

            rmdir /lib/plymouth/themes || :
            rmdir /lib/plymouth || :

            update-initramfs -u
	;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
	printf "%s\\n" "${0} called with unknown argument \`${1}'" 1>&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
